sudo: required

language: php

branches:
    only:
        - master
        - php7
        - php5
        - v0.0.2

notifications:
    slack:
        secure: tgQIiODFrpQ3pUCMTCPfmG+UmI+G04uMplkeomH6qKAPvfB003lf4Dt6Z0Fr0khdAxNa+bbOmaKCF3BLyJ6gcWT9fZAYeXyz0Dk3tzEjhihWwDxoRUJRoY5XldoHyeWo4fXw3tfQE6DWZ9ixyfWKMNaCx7At6cwMl/AMgDrQfm2UDS/MxYiWMMDW920vABDV9DSfsvrkC+6tcHYCOnjwS27R9Z0rDfeykJ2zKBDdgh7Em1/TX8z/pr1FJk1oVrVjOrUoNu729Jn/PfVkMSAAuWwpIk6iMzBr6dVuj6qVlYENMiwBJJ+7J5ERrCxbi6JbKJf8WRhc36nVHzz/X9onHaTzgBCDNAHtWWjm15Krb0HXeSkLcXi+GEsllJDCAVriwRpGAre/QUZHzIk2jCQUfOiiVrsyE2yJjPMJ3Zpa23oYKWA8nh/51BQoa9lL3TgZFUxqqtK2RU4ZSMDDdiLhQr5LhFPlMzPIKfYvV3Cqdg74jcq9WnWq4DFyCCfh7Kd5g5P6tAEV10wx+XHkfbczgd/KWFs7S8mo8qE7b7sAnJpgDH3B//4h2TVzZRw1BWrysdzH0O4uTBVfr3Lh0SiRschAW5uNBSHBaEN/N7IBuDNoMMPEiqoLeYLVnIVqHOvBVWkxkU6HxE/iW412Xf2CDTrQyWIlaSlnIphf4bZf8y0=

services:
    - docker

before_install:
    - docker build -t mkenney/php-base:travis-ci .
    - cd test

script:
    - docker run --rm -ti -v $(pwd):/src:rw mkenney/php-base:travis-ci --version
    - docker run --rm -ti -v $(pwd):/src:rw mkenney/php-base:travis-ci ./testGdSupport.php
